# Generated by Django 6.0.7 on 2026-07-18 13:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0003_align_gametitle_schema'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='gametitle',
            options={'ordering': ['name'], 'verbose_name': 'Game Title', 'verbose_name_plural': 'Game Titles'},
        ),
        migrations.AlterUniqueTogether(
            name='gametitle',
            unique_together=set(),
        ),
        migrations.AlterField(
            model_name='gametitle',
            name='name',
            field=models.CharField(max_length=255, unique=True),
        ),
        migrations.AlterField(
            model_name='gametitle',
            name='source',
            field=models.CharField(blank=True, default='', max_length=100),
        ),
        migrations.RemoveField(
            model_name='gametitle',
            name='external_id',
        ),
        migrations.RemoveField(
            model_name='gametitle',
            name='platform',
        ),
        migrations.RemoveField(
            model_name='gametitle',
            name='show_in_selector',
        ),
    ]
