# Generated by Django 6.0.7 on 2026-07-19 07:53

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0004_alter_gametitle_options_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='Personnel',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=150, unique=True, verbose_name='نام')),
                ('is_active', models.BooleanField(default=True, verbose_name='فعال')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'verbose_name': 'پرسنل',
                'verbose_name_plural': 'پرسنل',
                'ordering': ['name'],
            },
        ),
        migrations.CreateModel(
            name='Product',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200, verbose_name='نام کالا')),
                ('category', models.CharField(choices=[('console', 'کنسول'), ('controller', 'کنترلر'), ('accessory', 'لوازم جانبی'), ('game', 'بازی'), ('digital_account', 'اکانت دیجیتال'), ('other', 'سایر')], default='console', max_length=30, verbose_name='دسته\u200cبندی')),
                ('is_active', models.BooleanField(default=True, verbose_name='فعال')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'verbose_name': 'کالا',
                'verbose_name_plural': 'کالاها',
                'ordering': ['category', 'name'],
                'unique_together': {('name', 'category')},
            },
        ),
        migrations.CreateModel(
            name='PurchaseRecord',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('serial_number', models.CharField(blank=True, default='', max_length=150, verbose_name='شماره سریال')),
                ('quantity', models.PositiveIntegerField(default=1, verbose_name='تعداد')),
                ('unit_price', models.PositiveBigIntegerField(default=0, verbose_name='قیمت واحد (تومان)')),
                ('supplier_name', models.CharField(blank=True, default='', max_length=200, verbose_name='فروشنده (تأمین\u200cکننده)')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='تاریخ و ساعت ثبت')),
                ('product', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='purchases', to='app.product', verbose_name='کالا')),
                ('receiver', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='purchases_received', to='app.personnel', verbose_name='دریافت\u200cکننده')),
            ],
            options={
                'verbose_name': 'رکورد خرید',
                'verbose_name_plural': 'رکوردهای خرید',
                'ordering': ['-created_at'],
            },
        ),
    ]
