# Generated by Django 6.0.7 on 2026-07-20 10:36

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0006_bankaccount_devicename_installer_saleterm_supplier_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='InventoryItem',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('serial_number', models.CharField(max_length=150, unique=True, verbose_name='شماره سریال')),
                ('unit_cost', models.PositiveBigIntegerField(default=0, verbose_name='قیمت خرید (ریال)')),
                ('status', models.CharField(choices=[('in_stock', 'در انبار'), ('sold', 'فروخته\u200cشده')], default='in_stock', max_length=20, verbose_name='وضعیت')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='تاریخ ورود به انبار')),
                ('sold_at', models.DateTimeField(blank=True, null=True, verbose_name='تاریخ فروش')),
                ('device_name', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='inventory_items', to='app.devicename', verbose_name='نام دستگاه')),
                ('device_type', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='inventory_items', to='app.devicetype', verbose_name='نوع دستگاه')),
                ('purchase', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='inventory_items', to='app.purchaserecord', verbose_name='از خرید')),
                ('sale_line_item', models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='inventory_item', to='app.salelineitem', verbose_name='ردیف فروش')),
            ],
            options={
                'verbose_name': 'واحد موجودی',
                'verbose_name_plural': 'واحدهای موجودی',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='StockLevel',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('quantity', models.IntegerField(default=0, verbose_name='موجودی')),
                ('device_name', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='stock_levels', to='app.devicename', verbose_name='نام دستگاه')),
                ('device_type', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='stock_levels', to='app.devicetype', verbose_name='نوع دستگاه')),
            ],
            options={
                'verbose_name': 'موجودی (فله\u200cای)',
                'verbose_name_plural': 'موجودی\u200cهای فله\u200cای',
                'unique_together': {('device_name', 'device_type')},
            },
        ),
    ]
