# Generated by Django 6.0.7 on 2026-07-21 08:22

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0008_accessory_accessorybrand_accessorycolor_deviceregion_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='gametitle',
            name='platforms',
        ),
        migrations.AddField(
            model_name='gameinstallorder',
            name='license_type',
            field=models.CharField(choices=[('license', 'لایسنس'), ('copy', 'کپی')], default='copy', max_length=10, verbose_name='لایسنس / کپی'),
        ),
        migrations.CreateModel(
            name='GamePlatformAvailability',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('license_type', models.CharField(choices=[('license', 'لایسنس'), ('copy', 'کپی')], max_length=10, verbose_name='نوع')),
                ('device_name', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='game_availabilities', to='app.devicename', verbose_name='دستگاه')),
                ('game', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='availabilities', to='app.gametitle', verbose_name='بازی')),
            ],
            options={
                'verbose_name': 'دسترسی بازی',
                'verbose_name_plural': 'دسترسی\u200cهای بازی',
                'unique_together': {('game', 'device_name', 'license_type')},
            },
        ),
    ]
