# Generated by Django 6.0.7 on 2026-07-21 08:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0009_remove_gametitle_platforms_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='gametitle',
            name='platforms',
            field=models.ManyToManyField(blank=True, related_name='game_titles', through='app.GamePlatformAvailability', to='app.devicename', verbose_name='پلتفرم\u200cهای سازگار'),
        ),
    ]
