# Generated by Django 6.0.7 on 2026-07-25 08:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0011_salelineitem_accessory_salelineitem_device_region_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='salerecord',
            name='change',
            field=models.BooleanField(default=False, verbose_name='تعویض (Change)'),
        ),
    ]
