# Generated by Django 6.0.7 on 2026-08-14 00:07

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0020_merge_20260811_1404'),
        ('app', '0021_unify_prices_to_toman'),
    ]

    operations = [
    ]
