# Generated by Django 6.0.7 on 2026-07-12 10:44

import django.db.models.deletion
import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Device',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('serial_number', models.CharField(max_length=100, unique=True, verbose_name='سریال')),
                ('name', models.CharField(max_length=100, verbose_name='نام دستگاه')),
                ('category', models.CharField(choices=[('console', 'کنسول'), ('acc', 'اکسسوری'), ('game', 'بازی')], default='console', max_length=50)),
            ],
        ),
        migrations.CreateModel(
            name='Transaction',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('entry_date', models.DateTimeField(default=django.utils.timezone.now, verbose_name='تاریخ ورود')),
                ('purpose', models.CharField(max_length=50, verbose_name='علت ورود')),
                ('sender', models.CharField(max_length=100, verbose_name='فرستنده')),
                ('receiver_entry', models.CharField(max_length=100, verbose_name='گیرنده ورود')),
                ('exit_date', models.DateTimeField(blank=True, null=True, verbose_name='تاریخ خروج')),
                ('result', models.CharField(blank=True, max_length=100, null=True, verbose_name='نتیجه خروج')),
                ('description', models.TextField(blank=True)),
                ('device', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='history', to='app.device')),
            ],
        ),
    ]
