# Generated by Django 6.0.7 on 2026-07-15 12:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='transaction',
            name='device',
        ),
        migrations.CreateModel(
            name='GameTitle',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255)),
                ('platform', models.CharField(choices=[('PS4', 'PS4'), ('PS5', 'PS5'), ('Xbox One', 'Xbox One'), ('Xbox Series X', 'Xbox Series X'), ('Nintendo Switch', 'Nintendo Switch')], max_length=50)),
                ('show_in_selector', models.BooleanField(default=True)),
                ('source', models.CharField(default='manual', max_length=50)),
                ('external_id', models.CharField(blank=True, max_length=100, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'ordering': ['platform', 'name'],
                'unique_together': {('name', 'platform')},
            },
        ),
        migrations.DeleteModel(
            name='Device',
        ),
        migrations.DeleteModel(
            name='Transaction',
        ),
    ]
