# Generated by Django 6.0.7 on 2026-07-20 08:35

import django.db.models.deletion
import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0005_personnel_product_purchaserecord'),
    ]

    operations = [
        migrations.CreateModel(
            name='BankAccount',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('label', models.CharField(max_length=150, unique=True, verbose_name='عنوان حساب')),
                ('is_active', models.BooleanField(default=True, verbose_name='فعال')),
                ('order', models.PositiveIntegerField(default=0, verbose_name='ترتیب نمایش')),
            ],
            options={
                'verbose_name': 'حساب بانکی',
                'verbose_name_plural': 'حساب\u200cهای بانکی',
                'ordering': ['order', 'label'],
            },
        ),
        migrations.CreateModel(
            name='DeviceName',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, unique=True, verbose_name='نام دستگاه')),
                ('is_active', models.BooleanField(default=True, verbose_name='فعال')),
                ('order', models.PositiveIntegerField(default=0, verbose_name='ترتیب نمایش')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'verbose_name': 'نام دستگاه',
                'verbose_name_plural': 'نام\u200cهای دستگاه',
                'ordering': ['order', 'name'],
            },
        ),
        migrations.CreateModel(
            name='Installer',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=150, unique=True, verbose_name='نام نصاب')),
                ('is_active', models.BooleanField(default=True, verbose_name='فعال')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'verbose_name': 'نصاب',
                'verbose_name_plural': 'نصاب\u200cها',
                'ordering': ['name'],
            },
        ),
        migrations.CreateModel(
            name='SaleTerm',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('text', models.CharField(max_length=200, unique=True, verbose_name='متن شرط')),
                ('is_active', models.BooleanField(default=True, verbose_name='فعال')),
                ('order', models.PositiveIntegerField(default=0, verbose_name='ترتیب نمایش')),
            ],
            options={
                'verbose_name': 'شرط فروش',
                'verbose_name_plural': 'شرایط فروش',
                'ordering': ['order', 'text'],
            },
        ),
        migrations.CreateModel(
            name='Supplier',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200, unique=True, verbose_name='نام تأمین\u200cکننده')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'verbose_name': 'تأمین\u200cکننده',
                'verbose_name_plural': 'تأمین\u200cکنندگان',
                'ordering': ['name'],
            },
        ),
        migrations.RemoveField(
            model_name='purchaserecord',
            name='product',
        ),
        migrations.RemoveField(
            model_name='purchaserecord',
            name='supplier_name',
        ),
        migrations.AddField(
            model_name='personnel',
            name='is_admin',
            field=models.BooleanField(default=False, verbose_name='دسترسی مدیر'),
        ),
        migrations.AlterField(
            model_name='purchaserecord',
            name='created_at',
            field=models.DateTimeField(default=django.utils.timezone.now, verbose_name='تاریخ و ساعت ثبت'),
        ),
        migrations.AlterField(
            model_name='purchaserecord',
            name='unit_price',
            field=models.PositiveBigIntegerField(default=0, verbose_name='قیمت واحد (ریال)'),
        ),
        migrations.AddField(
            model_name='gametitle',
            name='platforms',
            field=models.ManyToManyField(blank=True, related_name='game_titles', to='app.devicename', verbose_name='پلتفرم\u200cهای سازگار'),
        ),
        migrations.AddField(
            model_name='purchaserecord',
            name='device_name',
            field=models.ForeignKey(default='', on_delete=django.db.models.deletion.PROTECT, related_name='purchases', to='app.devicename', verbose_name='نام دستگاه'),
            preserve_default=False,
        ),
        migrations.CreateModel(
            name='DeviceType',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, verbose_name='نوع دستگاه')),
                ('is_active', models.BooleanField(default=True, verbose_name='فعال')),
                ('order', models.PositiveIntegerField(default=0, verbose_name='ترتیب نمایش')),
                ('device_name', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='types', to='app.devicename', verbose_name='نام دستگاه')),
            ],
            options={
                'verbose_name': 'نوع دستگاه',
                'verbose_name_plural': 'نوع\u200cهای دستگاه',
                'ordering': ['device_name__order', 'order', 'name'],
                'unique_together': {('device_name', 'name')},
            },
        ),
        migrations.AddField(
            model_name='purchaserecord',
            name='device_type',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='purchases', to='app.devicetype', verbose_name='نوع دستگاه'),
        ),
        migrations.CreateModel(
            name='GameInstallOrder',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('customer_name', models.CharField(blank=True, default='', max_length=200, verbose_name='نام مشتری')),
                ('serial_number', models.CharField(blank=True, default='', max_length=150, verbose_name='شماره سریال دستگاه')),
                ('order_datetime', models.DateTimeField(default=django.utils.timezone.now, verbose_name='تاریخ و ساعت سفارش')),
                ('referred_at', models.DateTimeField(default=django.utils.timezone.now, verbose_name='تاریخ و ساعت ارجاع به نصاب')),
                ('return_at', models.DateTimeField(blank=True, null=True, verbose_name='تاریخ و ساعت بازگشت')),
                ('install_cost', models.PositiveBigIntegerField(default=0, verbose_name='هزینه نصب (تومان)')),
                ('delivered', models.BooleanField(default=False, verbose_name='تحویل داده شد')),
                ('delivered_at', models.DateTimeField(blank=True, null=True, verbose_name='تاریخ و ساعت تحویل')),
                ('device_name', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='install_orders', to='app.devicename', verbose_name='نام دستگاه')),
                ('game_slot_1', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to='app.gametitle', verbose_name='بازی ۱')),
                ('game_slot_10', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to='app.gametitle', verbose_name='بازی ۱۰')),
                ('game_slot_2', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to='app.gametitle', verbose_name='بازی ۲')),
                ('game_slot_3', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to='app.gametitle', verbose_name='بازی ۳')),
                ('game_slot_4', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to='app.gametitle', verbose_name='بازی ۴')),
                ('game_slot_5', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to='app.gametitle', verbose_name='بازی ۵')),
                ('game_slot_6', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to='app.gametitle', verbose_name='بازی ۶')),
                ('game_slot_7', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to='app.gametitle', verbose_name='بازی ۷')),
                ('game_slot_8', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to='app.gametitle', verbose_name='بازی ۸')),
                ('game_slot_9', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to='app.gametitle', verbose_name='بازی ۹')),
                ('receiver', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='install_orders_received', to='app.personnel', verbose_name='کاربر')),
                ('installer', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='install_orders', to='app.installer', verbose_name='نصاب')),
            ],
            options={
                'verbose_name': 'سفارش نصب بازی',
                'verbose_name_plural': 'سفارش\u200cهای نصب بازی',
                'ordering': ['-order_datetime'],
            },
        ),
        migrations.CreateModel(
            name='SaleRecord',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('customer_name', models.CharField(blank=True, default='', max_length=200, verbose_name='نام مشتری')),
                ('customer_national_id', models.CharField(blank=True, default='', max_length=20, verbose_name='کد ملی مشتری')),
                ('customer_phone', models.CharField(blank=True, default='', max_length=20, verbose_name='شماره تماس مشتری')),
                ('created_at', models.DateTimeField(default=django.utils.timezone.now, verbose_name='تاریخ و ساعت ثبت')),
                ('seller', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='sales_made', to='app.personnel', verbose_name='فروشنده')),
                ('terms', models.ManyToManyField(blank=True, related_name='sales', to='app.saleterm', verbose_name='شرایط فروش')),
            ],
            options={
                'verbose_name': 'فاکتور فروش',
                'verbose_name_plural': 'فاکتورهای فروش',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='SaleLineItem',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('serial_number', models.CharField(blank=True, default='', max_length=150, verbose_name='شماره سریال')),
                ('quantity', models.PositiveIntegerField(default=1, verbose_name='تعداد')),
                ('unit_price', models.PositiveBigIntegerField(default=0, verbose_name='قیمت واحد (تومان)')),
                ('device_name', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='sale_items', to='app.devicename', verbose_name='نام دستگاه')),
                ('device_type', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='sale_items', to='app.devicetype', verbose_name='نوع دستگاه')),
                ('sale', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='items', to='app.salerecord', verbose_name='فاکتور')),
            ],
            options={
                'verbose_name': 'ردیف فاکتور فروش',
                'verbose_name_plural': 'ردیف\u200cهای فاکتور فروش',
            },
        ),
        migrations.CreateModel(
            name='Payment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('payment_type', models.CharField(choices=[('pos', 'پوز (کارتخوان)'), ('transfer', 'انتقال بانکی')], max_length=20, verbose_name='نوع پرداخت')),
                ('amount', models.PositiveBigIntegerField(default=0, verbose_name='مبلغ (تومان)')),
                ('tracking_number', models.CharField(blank=True, default='', max_length=100, verbose_name='شماره پیگیری')),
                ('bank_account', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='payments', to='app.bankaccount', verbose_name='حساب مقصد')),
                ('sale', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='payments', to='app.salerecord', verbose_name='فاکتور')),
            ],
            options={
                'verbose_name': 'پرداخت',
                'verbose_name_plural': 'پرداخت\u200cها',
            },
        ),
        migrations.AddField(
            model_name='purchaserecord',
            name='supplier',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='purchases', to='app.supplier', verbose_name='تأمین\u200cکننده'),
        ),
    ]
