# Generated by Django 6.0.7 on 2026-07-21 08:06

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0007_inventoryitem_stocklevel'),
    ]

    operations = [
        migrations.CreateModel(
            name='Accessory',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200, verbose_name='نام کالا')),
                ('model', models.CharField(blank=True, default='', max_length=200, verbose_name='مدل')),
                ('is_active', models.BooleanField(default=True, verbose_name='فعال')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'verbose_name': 'کالای جانبی',
                'verbose_name_plural': 'کالاهای جانبی',
                'ordering': ['name'],
            },
        ),
        migrations.CreateModel(
            name='AccessoryBrand',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=150, unique=True, verbose_name='نام برند')),
            ],
            options={
                'verbose_name': 'برند لوازم جانبی',
                'verbose_name_plural': 'برندهای لوازم جانبی',
                'ordering': ['name'],
            },
        ),
        migrations.CreateModel(
            name='AccessoryColor',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, unique=True, verbose_name='رنگ')),
            ],
            options={
                'verbose_name': 'رنگ لوازم جانبی',
                'verbose_name_plural': 'رنگ\u200cهای لوازم جانبی',
                'ordering': ['name'],
            },
        ),
        migrations.CreateModel(
            name='DeviceRegion',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('code', models.CharField(max_length=20, unique=True, verbose_name='کد ریژن')),
                ('is_active', models.BooleanField(default=True, verbose_name='فعال')),
                ('order', models.PositiveIntegerField(default=0, verbose_name='ترتیب نمایش')),
            ],
            options={
                'verbose_name': 'ریژن',
                'verbose_name_plural': 'ریژن\u200cها',
                'ordering': ['order', 'code'],
            },
        ),
        migrations.AddField(
            model_name='devicename',
            name='has_region',
            field=models.BooleanField(default=False, verbose_name='دارای ریژن'),
        ),
        migrations.AlterField(
            model_name='inventoryitem',
            name='device_name',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='inventory_items', to='app.devicename', verbose_name='نام دستگاه'),
        ),
        migrations.AlterField(
            model_name='purchaserecord',
            name='device_name',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='purchases', to='app.devicename', verbose_name='نام دستگاه'),
        ),
        migrations.AlterField(
            model_name='stocklevel',
            name='device_name',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='stock_levels', to='app.devicename', verbose_name='نام دستگاه'),
        ),
        migrations.AlterUniqueTogether(
            name='stocklevel',
            unique_together=set(),
        ),
        migrations.AddField(
            model_name='inventoryitem',
            name='accessory',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='inventory_items', to='app.accessory', verbose_name='کالای جانبی'),
        ),
        migrations.AddField(
            model_name='purchaserecord',
            name='accessory',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='purchases', to='app.accessory', verbose_name='کالای جانبی'),
        ),
        migrations.AddField(
            model_name='stocklevel',
            name='accessory',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='stock_levels', to='app.accessory', verbose_name='کالای جانبی'),
        ),
        migrations.AlterUniqueTogether(
            name='stocklevel',
            unique_together={('device_name', 'device_type', 'accessory')},
        ),
        migrations.AddField(
            model_name='accessory',
            name='brand',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='accessories', to='app.accessorybrand', verbose_name='برند'),
        ),
        migrations.AddField(
            model_name='accessory',
            name='color',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='accessories', to='app.accessorycolor', verbose_name='رنگ'),
        ),
        migrations.AddField(
            model_name='purchaserecord',
            name='device_region',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='purchases', to='app.deviceregion', verbose_name='ریژن'),
        ),
        migrations.CreateModel(
            name='DeviceVariant',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('code', models.CharField(max_length=50, verbose_name='کد/شماره سری')),
                ('is_active', models.BooleanField(default=True, verbose_name='فعال')),
                ('order', models.PositiveIntegerField(default=0, verbose_name='ترتیب نمایش')),
                ('device_type', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='variants', to='app.devicetype', verbose_name='نوع دستگاه')),
            ],
            options={
                'verbose_name': 'جزئیات نوع دستگاه',
                'verbose_name_plural': 'جزئیات نوع دستگاه',
                'ordering': ['order', 'code'],
                'unique_together': {('device_type', 'code')},
            },
        ),
        migrations.AddField(
            model_name='purchaserecord',
            name='device_variant',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='purchases', to='app.devicevariant', verbose_name='شماره سری'),
        ),
        migrations.AlterUniqueTogether(
            name='accessory',
            unique_together={('name', 'brand', 'model', 'color')},
        ),
    ]
