# Generated by Django 6.0.7 on 2026-07-22 11:41

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0010_gametitle_platforms'),
    ]

    operations = [
        migrations.AddField(
            model_name='salelineitem',
            name='accessory',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='sale_items', to='app.accessory', verbose_name='کالای جانبی'),
        ),
        migrations.AddField(
            model_name='salelineitem',
            name='device_region',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='sale_items', to='app.deviceregion', verbose_name='ریژن'),
        ),
        migrations.AddField(
            model_name='salelineitem',
            name='device_variant',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='sale_items', to='app.devicevariant', verbose_name='شماره سری'),
        ),
        migrations.AlterField(
            model_name='salelineitem',
            name='device_name',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='sale_items', to='app.devicename', verbose_name='نام دستگاه'),
        ),
    ]
