# Generated by Django 6.0.7 on 2026-07-27 10:05

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0012_salerecord_change'),
    ]

    operations = [
        migrations.CreateModel(
            name='ProductGroup',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, unique=True, verbose_name='نام گروه')),
                ('order', models.PositiveIntegerField(default=0, verbose_name='ترتیب نمایش')),
            ],
            options={
                'verbose_name': 'گروه محصول',
                'verbose_name_plural': 'گروه\u200cهای محصول',
                'ordering': ['order', 'name'],
            },
        ),
        migrations.AddField(
            model_name='devicetype',
            name='brand',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='device_types', to='app.accessorybrand', verbose_name='برند'),
        ),
        migrations.AddField(
            model_name='devicetype',
            name='color',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='device_types', to='app.accessorycolor', verbose_name='رنگ'),
        ),
        migrations.AddField(
            model_name='devicetype',
            name='condition',
            field=models.CharField(choices=[('new', 'نو'), ('used', 'استوک')], default='new', max_length=10, verbose_name='وضعیت'),
        ),
        migrations.AddField(
            model_name='devicename',
            name='group',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='device_names', to='app.productgroup', verbose_name='گروه'),
        ),
    ]
