# Generated by Django 6.0.7 on 2026-08-11 10:34

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0019_alter_party_id_alter_partyledgerentry_id'),
        ('app', '0019_gameinstallorder_customer_phone'),
    ]

    operations = [
    ]
