# Generated by Django 6.0.7 on 2026-08-14 08:21

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0022_merge_20260814_0337'),
        ('app', '0022_personnel_auth_permissions'),
    ]

    operations = [
    ]
